---

- hosts: webservers
  user: ubuntu
  sudo: True

  vars:
    app_name: hello_flask
    repo_url: https://github.com/mattupstate/ansible-tutorial.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv/webapps
    wsgi_file: wsgi.py
    wsgi_callable: app

  tasks:
    - name: ensure log directory
      file: dest={{ webapps_dir }}/{{ app_name }}/log state=directory

    - name: deploy code from repository
      git: repo={{ repo_url }} dest={{ webapps_dir }}/{{ app_name }}/src 
       remote={{ repo_remote }} version={{ repo_version }}

    - name: install dependencies into virtualenv
      pip: requirements={{ webapps_dir }}/{{ app_name }}/src/requirements.txt
       virtualenv={{ webapps_dir }}/{{ app_name }}/venv state=present

    - name: create supervisor program config
      template: src=templates/supervisor.conf dest=/etc/supervisor/supervisor.conf
      notify: restart app

    - name: create nginx site config
      template: src=templates/nginx_site.conf dest=/etc/nginx/sites-available/nginx_site.conf"
      notify: restart nginx

    - name: link nginx config
      file: src=/etc/nginx/sites-available/nginx_site.conf 
       dest=/etc/nginx/sites-enabled/nginx_site.conf state=link

    - name: start app
      supervisorctl: name={{ app_name }} state=started

  handlers:
    - name: restart app
      supervisorctl: name={{ app_name }} state=restarted

    - name: restart nginx
      service: name=nginx state=restarted
